export const PLUS_DAY_INTAKE = 'PLUS_DAY_INTAKE';

export const SET_TARGET_AMOUNT = 'SET_TARGET_AMOUNT';

export const ON_DATE_CHANGE = 'ON_DATE_CHANGE';

export const ON_INPUT_CHANGE = 'ON_INPUT_CHANGE';

export const SET_ERRORS = 'SET_ERRORS';

export const RESET_INPUT_VALUE = 'RESET_INPUT_VALUE';
